- name: app-setup
  include_role:
    name: common
    tasks_from: app-setup

- name: nodejs
  include_role:
    name: common
    tasks_from: nodejs

- name: systemd
  include_role:
    name: common
    tasks_from: systemd.yaml