  - name: install mysql
    ansible.builtin.dnf:
      name: mysql-server
      state: installed

  - name: start and enable mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: install boto3 and botocore
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
      - boto3
      - botocore

  - name: setup root password for mysql
    ansible.builtin.command: mysql_secure_installation --set-root-pass {{ MYSQL_ROOT_PASSWORD }}